config/routes.rb
RailsDevisePundit::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :tickets, except: [:index, :destroy] do
    resources :comments, except: [:index, :show, :edit, :destroy]
  end

  namespace :admin do
    get 'quick_jump', to: 'tickets#quick_jump'
    resources :tickets do
      get 'assign', to: 'assigments#update_assigment'
      resources :comments
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Relationships::TicketComment
  include Validations::Comment
end

app/models/concerns/validations/comment.rb
module Validations::Comment
  extend ActiveSupport::Concern

  included do
    validates_presence_of :body
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController

  before_action :set_ticket
  before_action :set_comment, except: [:index]

  def index
    @comments = @ticket.comments
    authorize @comments
  end

  def show
  end

  def new
  end

  def edit
    render :new
  end

  def create
    @comment.assign_attributes(comment_params)
    if @comment.save
      redirect_to action: :index, notice: 'Comment was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to action: :index, notice: 'Comment was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    Comment.find(params[:id]).destroy!
    redirect_to action: :index
  end

  private

  def set_ticket
    @ticket = Ticket.friendly.find(params[:ticket_id])
    authorize @ticket
  end

  def set_comment
    @comment = Comment.new
    if params[:id]
      @comment = @ticket.comments.find(params[:id])
    else
      @comment = @ticket.comments.new
    end
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:id, :ticket_id, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_ticket
  before_action :set_comment, except: [:index]

  def new
  end

  def create
    @comment.assign_attributes(comment_params)
    if @comment.save
      redirect_to ticket_path(@ticket), notice: 'Comment was successfully created.'
    else
      render action: :new
    end
  end

  private

  def set_ticket
    @ticket = Ticket.friendly.find(params[:ticket_id])
  end

  def set_comment
    @comment = Comment.new
    if params[:id]
      @comment = @ticket.comments.find(params[:id])
    else
      @comment = @ticket.comments.new
    end
  end

  def comment_params
    params.require(:comment).permit(:id, :ticket_id, :body)
  end
end

app/views/admin/comments/_form.html.haml
=form_for [:admin, @ticket, @comment] do |f|
  = f.hidden_field :id
  = f.hidden_field :ticket_id
  %ul
    %li= f.label :body, 'Comment description'
    %li= f.text_area :body
  =f.submit

app/views/admin/comments/index.html.haml
.block
  .content
    %h2= 'Comments'
    %table.table
      %th= 'Comment data'
      %th= 'Created at'
      %th= 'Actions'
      - @comments.each do |comment|
        = render partial: 'admin/comments/detail/teaser', locals: {comment: comment}
    = link_to 'Add new', new_admin_ticket_comment_path(@ticket)
    = link_to 'Back to tickets', admin_tickets_path

app/views/admin/comments/new.html.haml
.block
  .content
    .form
      = render partial: 'admin/errors/error_messages', locals: { entity: @comment }
      = render partial: 'form'
    =link_to 'Back', admin_ticket_comments_path(@ticket)