config/routes.rb
RailsDevisePundit::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :tickets, except: [:index, :destroy] do
    resources :comments, except: [:index, :show, :edit, :destroy]
  end

  namespace :admin do
    get 'quick_jump', to: 'tickets#quick_jump'
    resources :tickets do
      get 'assign', to: 'assigments#update_assigment'
      resources :comments
    end
  end
end

app/models/concerns/relationships/ticket.rb
module Relationships::Ticket
  extend ActiveSupport::Concern

  included do
    has_many :comments, dependent: :destroy
    belongs_to :ticket_status
    belongs_to :accepted_by, class_name: 'User'

    scope :assigned_to, lambda { |user| where(accepted_by_id: user) }
    scope :unassigned, -> { where(accepted_by_id: nil) }
  end
end

app/models/concerns/validations/ticket.rb
module Validations::Ticket
  extend ActiveSupport::Concern

  included do
    validates_uniqueness_of :slug
    validates_presence_of :title, :description, :customer_name, :customer_email
    validates :customer_email, format: /@/
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  extend FriendlyId
  include Relationships::Ticket
  include Validations::Ticket
  include TicketExt::Methods

  after_initialize :set_default_status
  after_create :send_mail


  protected

  def set_default_status
    self.ticket_status_id ||= 1
  end

  def send_mail
    TicketMailer.ticket_posted(self).deliver
  end

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < AdminController

  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :quick_jump]

  def quick_jump
    redirect_to action: :show, id: @ticket.id
  end

  def index
    @tickets = Ticket.all
    authorize @tickets
  end

  def show
  end

  def new
    @ticket = Ticket.new
    authorize @ticket
  end

  def edit
    render :new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    authorize @ticket
    if @ticket.save
      redirect_to action: :index, notice: 'Ticket was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to action: :index, notice: 'Ticket was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
    Ticket.friendly.find(params[:id]).destroy!
    redirect_to action: :index
  end

  private

  def set_ticket
    begin
      @ticket = Ticket.friendly.find(params[:id])
    rescue => e
      redirect_to action: :index, notice: 'Ticket not found' and return unless @ticket
    end
    authorize @ticket
  end

  def ticket_params
    params.require(:ticket).permit(:id, :ticket_status_id, :title, :description, :customer_name, :customer_email)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
    render :new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: 'Ticket was successfully created.'
    else
      render action: :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Ticket was successfully updated.'
    else
      render action: :edit
    end
  end

  private

    def set_ticket
      @ticket = Ticket.friendly.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:id, :title, :description, :customer_name, :customer_email)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_comments.html.haml
- if comments.present? && !comments.empty?
  %span= 'Comments:'
  %ul
    - comments.each do |comment|
      %li
        %span= comment.body
= link_to 'Add new', new_ticket_comment_path(@ticket)

app/views/tickets/_error_messages.html.haml
- if entity.errors.any?
  %ul.errors
    - entity.errors.full_messages.each do |msg|
      %li= msg

app/views/tickets/_form.html.haml
=form_for @ticket do |f|
  = f.hidden_field :id
  %ul
    %li= f.label :customer_name, 'Your name'
    %li= f.text_field :customer_name
    %li= f.label :customer_email, 'Your email'
    %li= f.text_field :customer_email
    %li= f.label :title, 'Ticket title'
    %li= f.text_field :title
    %li= f.label :description, 'Ticket description'
    %li= f.text_area :description
  =f.submit 'Post ticket'

app/views/tickets/new.html.haml
#content
  .form
    = render partial: 'error_messages', locals: { entity: @ticket }
    = render partial: 'form'
  =link_to 'Back', root_path

app/views/tickets/show.html.haml
#content
  %ul
    %li
      %span= "Status"
      %span= @ticket.ticket_status.title
    %li= @ticket.title
    %li= @ticket.description
    %li
      = render partial: 'comments', locals: { comments: @ticket.comments }
  =link_to 'Edit', edit_ticket_path(@ticket)
  =link_to 'Back to main page', root_path